### PR TITLE
merge tutorial eval-expressions into develop

### PR DESCRIPTION
**Pull request by jgeorges371**
I am updating the current tutorial on evaluating expressions to include a better resource for BEDMAS. The previous resource had the potential to mislead readers regarding the order in which to evaluate brackets.

I also updated the content of the tutorial. Specifically, the section that talks about terms because there were examples of `non-terms` that actually are terms.

I added an additional exercise that tests the reader's knowledge on evaluating inner brackets.

 Here is the link to preview the tutorial [http://mathbook.io/review/jgeorges371/eval-expressions](http://mathbook.io/review/jgeorges371/eval-expressions)

### CODE REVIEW

**Review by Gh0stByte — CHANGES_REQUESTED** [review]
I think that you should add below the 'not terms' that each piece on either side of the operator by themselves, however, are terms. Also in the sates, we use PEMDAS, which I located a [resource for](http://www.epcc.edu/OfficeofStudentSuccess/tutorialservices/tutorialsupportservicesMDP/Documents/Basic%20Math%20Handouts%20(PDF)/Math%20Handout%20(Basic)%20Pemdas%20(color).pdf)

Finally, I think maybe save mentioning the summation and product symbols unless you're going to explain them. 

Other than that, nice work!

**Comment by jgeorges371** [comment]
@Gh0stByte , thanks for the feedback. You make some great points. I also plan on adding another section discussing the value and purpose of expressions and their role in all areas in math.

**Comment by jgeorges371** [comment]
@Gh0stByte , I have made the changes you requested. Feel free to take a look and approve the PR if you think its ready.

Thanks.

**Review by Gh0stByte — APPROVED** [review]

**Comment by Gh0stByte** [comment]
Much improved! I especially appreciate the rewording in sections, and a more practical approach to the teaching,

**Pull request merged**
